version: '3'
services: 
  web-server:
    container_name: nginx-server
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - web-app
    ports:
      - 80:80
  web-app:
    container_name: hello-world
    build:
      context: ./app
      dockerfile: Dockerfile
    links:
      - database
    expose:
      - 9000
  database:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    expose:
      - 3306
    